FROM microsoft/dotnet:2.1-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk AS build
WORKDIR /src
COPY ["MarsRover/MarsRover.csproj", "MarsRover/"]
RUN dotnet restore "MarsRover/MarsRover.csproj"
COPY . .
WORKDIR "/src/MarsRover"
RUN dotnet build "MarsRover.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "MarsRover.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "MarsRover.dll"]